server:
  port: 8443
spring:  application:    name: API-Gateway  cloud:    gateway:      routes:      - id: CUSTOMER-MANAGEMENT-SERVICE
        uri: http://localhost:8081/
        predicates:        - Path=/customer-management-service/**          
      - id: ACCOUNT-MANAGEMENT-SERVICE
        uri: http://localhost:8082/
        predicates:        - Path=/account-management-service/**          
    
eureka:  instance:    prefer-ip-address: true
      client:    fetch-registry: true    register-with-eureka: true
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/
     
     
    